// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwubsmdmwaeibarmwgiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3dWJzbWRtd2FlaWJhcm13Z2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDgyOTksImV4cCI6MjA2OTEyNDI5OX0.aCZ0vIlZ3sWr-jQm5iAnf-hJc2sugP-Cx9TEj8jFvDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});